In [1]:
from pathlib import Path
import glob
import numpy as np
from scipy.io import loadmat
from scipy.io import wavfile
import os
from python_speech_features import mfcc
from python_speech_features import logfbank
from numpy import asarray
from numpy import savetxt
import arff
import pywt
import pandas as pd
from numpy import genfromtxt
import os 

In [2]:
data_dir1 = Path('/home/sumona/DiseaseBased/AR/FullRecordingAR/')
AR=[]
for filename in glob.glob(os.path.join(data_dir1, '*.wav')):
    samplerate, data = wavfile.read(filename)
    AR.append(data)
AR=np.asarray(AR)
print(AR)
#savetxt('AR_recording.csv', AR)

[[    0     0     0 ... -1119 -1134 -1153]
 [    0     0     0 ...  -710  -729  -746]
 [    0     0     0 ... -2194 -2152 -2112]
 ...
 [    0     0     0 ...  2857  2276  1699]
 [    0     0     0 ... -6925 -7037 -7181]
 [    0     0     0 ...  -339  -345  -351]]


In [3]:
data_dir2 = Path('/home/sumona/DiseaseBased/AS/FullRecordingAS/')
AS=[]
for filename in glob.glob(os.path.join(data_dir2, '*.wav')):
    samplerate, data = wavfile.read(filename)
    AS.append(data)
AS=np.asarray(AS)
print(AS)  
#savetxt('AS_recording.csv', AS)

[[    0     0     0 ... -2217 -2305 -2398]
 [    0    -1    -3 ...   905   907   909]
 [    0     0    -1 ...   259   175    88]
 ...
 [    0     0     0 ...  -892  -636  -371]
 [    0     0     0 ...  6285  6248  6206]
 [    0     0     0 ...  -394  -617  -835]]


In [4]:
data_dir3 = Path('/home/sumona/DiseaseBased/MR/FullRecordingMR/')
MR=[]
for filename in glob.glob(os.path.join(data_dir3, '*.wav')):
    samplerate, data = wavfile.read(filename)
    MR.append(data)
MR=np.asarray(MR)
print(MR)    
#savetxt('MR_recording.csv', MR)

[[    0     0     0 ...  6008  6167  6314]
 [    0     0     0 ...   441  -147  -765]
 [    0     0     0 ... -4354 -4593 -4834]
 ...
 [    0     0     0 ... -1468 -1485 -1504]
 [    0     0     0 ...  1030  1060  1084]
 [    0     0     0 ...  2198  2113  2032]]


In [5]:
data_dir4 = Path('/home/sumona/DiseaseBased/MS/FullRecordingMS/')
MS=[]
for filename in glob.glob(os.path.join(data_dir4, '*.wav')):
    samplerate, data = wavfile.read(filename)
    MS.append(data)
     
MS=np.asarray(MS)
print(MS) 
#savetxt('MS_recording.csv', MS)

[[    0     0    -1 ...   -46   -23    15]
 [    0     0     0 ... -3622 -3627 -3631]
 [    0     0     0 ...  8249  8048  7806]
 ...
 [    0     0     0 ...    48    40    33]
 [    0     0     0 ... 10461 10972 11530]
 [    0     0     0 ...  1350  1507  1662]]


In [16]:
##Opensmile feature extraction
f_mat=np.empty([1,384])
l_mat=np.array([])
for i in range(1,33):
 loc='/home/sumona/DiseaseBased/AR/FullRecordingAR/{}.wav.arff'.format(i)
 dataset=arff.load(open(loc, 'r'))
 data=np.array(dataset['data'])
 attributes = dataset['attributes']
 a=data
 a=np.delete(a,0,1)
 a=np.delete(a,384,1)
 f_mat=np.append(f_mat,a,axis=0)
 l_mat=np.append(l_mat,[1])
f_mat=np.delete(f_mat,0,0)
l_mat=np.append(l_mat,[],0)


for i in range(1,81):
 loc='/home/sumona/DiseaseBased/MR/FullRecordingMR/{}.wav.arff'.format(i)
 dataset=arff.load(open(loc, 'r'))
 data=np.array(dataset['data'])
 attributes = dataset['attributes']
 a=data
 a=np.delete(a,0,1)
 a=np.delete(a,384,1)
 f_mat=np.append(f_mat,a,axis=0)
 l_mat=np.append(l_mat,[2])

for i in range(1,81):
 loc='/home/sumona/DiseaseBased/AS/FullRecordingAS/{}.wav.arff'.format(i)
 dataset=arff.load(open(loc, 'r'))
 data=np.array(dataset['data'])
 attributes = dataset['attributes']
 a=data
 a=np.delete(a,0,1)
 a=np.delete(a,384,1)
 f_mat=np.append(f_mat,a,axis=0)
 l_mat=np.append(l_mat,[3])

for i in range(1,109):
 loc='/home/sumona/DiseaseBased/MS/FullRecordingMS/{}.arff'.format(i)
 dataset=arff.load(open(loc, 'r'))
 data=np.array(dataset['data'])
 attributes = dataset['attributes']
 a=data
 a=np.delete(a,0,1)
 a=np.delete(a,384,1)
 f_mat=np.append(f_mat,a,axis=0)
 l_mat=np.append(l_mat,[4])


print(l_mat.shape)
print(f_mat.shape)

(300,)
(300, 384)


In [7]:
##DWT Features
CA=np.empty([1,40000])
CD=np.empty([1,40000])
cA1, cD1 = pywt.dwt(AR, 'db1')
cA2, cD2 = pywt.dwt(MR, 'db1')
cA3, cD3 = pywt.dwt(AS, 'db1')
cA4, cD4 = pywt.dwt(MS, 'db1')
CA=np.append(CA,cA1,axis=0)
CA=np.delete(CA,0,0)
CA=np.append(CA,cA2,axis=0)
CA=np.append(CA,cA3,axis=0)
CA=np.append(CA,cA4,axis=0)
CD=np.append(CD,cD1,axis=0)
CD=np.delete(CD,0,0)
CD=np.append(CD,cD2,axis=0)
CD=np.append(CD,cD3,axis=0)
CD=np.append(CD,cD4,axis=0)


In [8]:
p=np.concatenate((CA,CD),axis=1)
features=np.concatenate((f_mat,p), axis=1)

In [9]:
##Time features

def data(path):
 my_data = genfromtxt(path, delimiter=',')
 return(my_data)

def tfeature(path):
    data1=data(path)
    return(data1)

In [10]:
path1='/home/sumona/DiseaseBased/'
path1=os.path.join(path1,'Time_Features_AR_unsegmented.csv')
t1=tfeature(path1)
t1=np.delete(t1,0,0)
path2='/home/sumona/DiseaseBased/'
path2=os.path.join(path2,'Time_Features_MR_unsegmented.csv')
t2=tfeature(path2)
t2=np.delete(t2,0,0)
path3='/home/sumona/DiseaseBased/'
path3=os.path.join(path3,'Time_Features_AS_unsegmented.csv')
t3=tfeature(path3)
t3=np.delete(t3,0,0)
path4='/home/sumona/DiseaseBased/'
path4=os.path.join(path4,'Time_Features_MS_unsegmented.csv')
t4=tfeature(path4)
t4=np.delete(t4,0,0)

In [11]:
q=np.concatenate((t1,t2),axis=0)
w=np.concatenate((q,t3),axis=0)
timefeatures=np.concatenate((w,t4),axis=0)

In [12]:
features=np.concatenate((features,timefeatures), axis=1)

In [13]:
features=pd.DataFrame(features)

In [14]:
savetxt('features_recording_dwt_mfcc_time.csv', features)

In [15]:
print(l_mat)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
